// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNvKnlr-6GSf3mXGlLh6qtU66mL3q484',
    appId: '1:623073638897:web:c7ed69aa24cdd8f348ac50',
    messagingSenderId: '623073638897',
    projectId: 'mynotes-dumb-flutter-backend',
    authDomain: 'mynotes-dumb-flutter-backend.firebaseapp.com',
    storageBucket: 'mynotes-dumb-flutter-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEYGC4a_PfUgH4YaQ0x2X2JTR0oGwNoU',
    appId: '1:623073638897:android:b517e05b223813ee48ac50',
    messagingSenderId: '623073638897',
    projectId: 'mynotes-dumb-flutter-backend',
    storageBucket: 'mynotes-dumb-flutter-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkP-uWcojIw7VX8kCHhtUSUamTMFQSgk8',
    appId: '1:623073638897:ios:ea7218c4dfdda51c48ac50',
    messagingSenderId: '623073638897',
    projectId: 'mynotes-dumb-flutter-backend',
    storageBucket: 'mynotes-dumb-flutter-backend.appspot.com',
    iosClientId: '623073638897-tdqgqda3n8grrdvtsec6e761dt81j0nh.apps.googleusercontent.com',
    iosBundleId: 'tn.blueberrybird.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkP-uWcojIw7VX8kCHhtUSUamTMFQSgk8',
    appId: '1:623073638897:ios:ea7218c4dfdda51c48ac50',
    messagingSenderId: '623073638897',
    projectId: 'mynotes-dumb-flutter-backend',
    storageBucket: 'mynotes-dumb-flutter-backend.appspot.com',
    iosClientId: '623073638897-tdqgqda3n8grrdvtsec6e761dt81j0nh.apps.googleusercontent.com',
    iosBundleId: 'tn.blueberrybird.mynotes',
  );
}
